---
abstract: 'Creates a boss which feeds a queue consumed by workers.'
author:
  - 'Kal Aeolian <kalielaeolian@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thread-Workers
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.06
